/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class FrmAddFriend extends javax.swing.JFrame {
    private DefaultListModel listModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAddFriend.class.getName());

    /**
     * Creates new form frmAddFriend
     */
    public FrmAddFriend() {
        initComponents();
        setLocationRelativeTo(null);
        lblUser.setText(" " + AppData.loggedOn.basicInfo());
        setupListBox();
    }
    
    public void setupListBox() {
        listModel = new DefaultListModel();
        
        for (Object obj : AppData.usersAL) {
            User tmpUser = (User) obj;
            if(tmpUser.getUserID() != AppData.loggedOn.getUserID())
                listModel.addElement(tmpUser.basicInfo());
        }//for-each
        
        lstUsers.setModel(listModel);
    }//setupListBox
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsers = new javax.swing.JList<>();
        btnAdd = new javax.swing.JButton();
        lblDetails = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblUsers = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lstUsers.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lstUsers.setForeground(new java.awt.Color(0, 102, 204));
        lstUsers.setPreferredSize(new java.awt.Dimension(260, 270));
        lstUsers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstUsersValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsers);

        btnAdd.setBackground(new java.awt.Color(0, 102, 204));
        btnAdd.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Friend");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblDetails.setBackground(new java.awt.Color(255, 255, 255));
        lblDetails.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        lblDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDetails.setToolTipText("");
        lblDetails.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblDetails.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblDetails.setOpaque(true);
        lblDetails.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 0));
        lblUser.setText("lblUser");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblUser.setOpaque(true);

        lblUsers.setBackground(new java.awt.Color(255, 255, 255));
        lblUsers.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(0, 102, 204));
        lblUsers.setText(" Suggestions");
        lblUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblUsers.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblUsers)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        AppData.friendsMenuScreen.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void lstUsersValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstUsersValueChanged
        String userInfo = listModel.get(lstUsers.getSelectedIndex()).toString();
        int uid = Integer.valueOf(userInfo.substring(1, 5));
        User found = AppData.findUser(uid);
        lblDetails.setText("<html>" + found.basicInfo()
                + "<br><br>Date of Birth: " + found.getDoB()
                + "<br><br>Date Registered: " + found.getRegDate()
                + "<br><br>Email: " + found.getEmail()
                + "<br><br>Last Online: " + found.getLastLogin() + "</html>");
    }//GEN-LAST:event_lstUsersValueChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String userInfo = listModel.get(lstUsers.getSelectedIndex()).toString();
        
            int fid = Integer.valueOf(userInfo.substring(1, 5));

            if (AppData.friendAlready(AppData.loggedOn.getUserID(), fid))
                //lblDetails.setText("You are already friends with this person!");
                JOptionPane.showMessageDialog(null, "You are already friends with this person!", "Already Friended", JOptionPane.OK_OPTION);
            else {
                Friend frd = new Friend (AppData.loggedOn.getUserID(), fid, AppData.genDateTime());
                AppData.friendsAL.add(frd);

                JOptionPane.showMessageDialog(null, "You and " + userInfo + " are now friends!", "Friend Added", JOptionPane.INFORMATION_MESSAGE);

                AppData.loggedOn.setFriends(AppData.loggedOn.getFriends() + 1);
            }//if-else
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "You haven't selected a user to add as a friend first!", "Pick Your Friend", JOptionPane.OK_OPTION);
        }//try-catch
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAddFriend().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JList<String> lstUsers;
    // End of variables declaration//GEN-END:variables
}
