
package oopa2;

import java.io.File;
import java.io.IOException;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;

public class FrmAddPost extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmAddPost.class.getName());

    /**
     * Creates new form frmAddPost
     */
    public FrmAddPost() {
        initComponents();
        setLocationRelativeTo(null);
        pnlImage.setVisible(false);
        pnlText.setVisible(true);
        setupCtrls();
    }//FrmAddPost

    public void setupCtrls() {
        int rnd = (int)(Math.random() * (99999 - 20001 + 1)) + 20001;
        while(AppData.isUniquePostID(rnd) == false)
            rnd = (int)(Math.random() * (99999 - 20001 + 1)) + 20001;
        
        String pid = String.valueOf(rnd);
        lblPostId.setText(pid);
        
        lblUser.setText(AppData.loggedOn.basicInfo());
        
        lblDateTime.setText(AppData.genDateTime());
        
        txtFilename.setText("");
        txtLocation.setText("");
        txtDescript.setText("");
        txtText.setText("");
    }//setupCtrls
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPic = new javax.swing.JLabel();
        btnAddPost = new javax.swing.JButton();
        cboPostSecurity = new javax.swing.JComboBox<>();
        cboPostType = new javax.swing.JComboBox<>();
        lblPostId = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        pnlImage = new javax.swing.JPanel();
        txtFilename = new javax.swing.JTextField();
        txtDescript = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblImage = new javax.swing.JLabel();
        btnPathInfo = new javax.swing.JButton();
        pnlText = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(722, 377));

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/blank-profile-picture-smaller.png"))); // NOI18N

        btnAddPost.setBackground(new java.awt.Color(0, 102, 204));
        btnAddPost.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnAddPost.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPost.setText("Post");
        btnAddPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPostActionPerformed(evt);
            }
        });

        cboPostSecurity.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        cboPostSecurity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Public", "Private" }));

        cboPostType.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        cboPostType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Text", "Image" }));
        cboPostType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboPostTypeActionPerformed(evt);
            }
        });

        lblPostId.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblPostId.setText("lblPostId");

        lblUser.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(102, 204, 0));
        lblUser.setText("lblUser");

        lblDateTime.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDateTime.setText("lblDateTime");

        pnlImage.setBackground(new java.awt.Color(255, 255, 255));
        pnlImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtFilename.setBackground(new java.awt.Color(255, 255, 255));
        txtFilename.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtFilename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtDescript.setBackground(new java.awt.Color(255, 255, 255));
        txtDescript.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtDescript.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtLocation.setBackground(new java.awt.Color(255, 255, 255));
        txtLocation.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        txtLocation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Description:");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Location:");

        lblImage.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lblImage.setForeground(new java.awt.Color(0, 102, 204));
        lblImage.setText("Attach Image");
        lblImage.setToolTipText("");
        lblImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblImage.setPreferredSize(new java.awt.Dimension(112, 21));

        btnPathInfo.setBackground(new java.awt.Color(0, 102, 204));
        btnPathInfo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnPathInfo.setForeground(new java.awt.Color(255, 255, 255));
        btnPathInfo.setText("Path Info");
        btnPathInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlImageLayout = new javax.swing.GroupLayout(pnlImage);
        pnlImage.setLayout(pnlImageLayout);
        pnlImageLayout.setHorizontalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlImageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlImageLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPathInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescript, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(txtLocation)
                                .addComponent(txtFilename)))))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        pnlImageLayout.setVerticalGroup(
            pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlImageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtFilename, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDescript, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLocation)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPathInfo)
                .addGap(15, 15, 15))
        );

        pnlText.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setBorder(null);

        txtText.setBackground(new java.awt.Color(255, 255, 255));
        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtText.setLineWrap(true);
        txtText.setRows(5);
        txtText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jScrollPane2.setViewportView(txtText);

        javax.swing.GroupLayout pnlTextLayout = new javax.swing.GroupLayout(pnlText);
        pnlText.setLayout(pnlTextLayout);
        pnlTextLayout.setHorizontalGroup(
            pnlTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        pnlTextLayout.setVerticalGroup(
            pnlTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPostId, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pnlText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 62, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cboPostType, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboPostSecurity, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAddPost, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDateTime)
                            .addComponent(lblPostId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddPost, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(cboPostType)
                    .addComponent(cboPostSecurity))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        AppData.mainScreen.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPostActionPerformed
        String secure = "public";
        if (cboPostSecurity.getSelectedIndex() == 1)
            secure = "private";
        
        String pType = "Text";
        if (cboPostType.getSelectedIndex() == 1)
            pType = "Image";
        
        int pid = Integer.valueOf(lblPostId.getText());
        int uid = Integer.valueOf((lblUser.getText()).substring(1, 5));
        
        if (pType.equals("Image")) {
            //int postID, int userID, String postSecurity, String date, String name, String description, String location
            
            Image obj = new Image(pid, uid, secure, lblDateTime.getText(), txtFilename.getText(), txtDescript.getText(), txtLocation.getText());
            AppData.postsAL.add(obj);
            
        }//if
        else {
            //int postID, int userID, String postSecurity, String date, String text
            //int uid = Integer.valueOf(lblUser.getText());
            
            Text obj = new Text(pid, uid, secure, lblDateTime.getText(), txtText.getText());
            AppData.postsAL.add(obj);
        }//if-else
        
        JOptionPane.showMessageDialog(null, pType + " successfully posted!", pType + "Post", JOptionPane.INFORMATION_MESSAGE);
        setupCtrls();
    }//GEN-LAST:event_btnAddPostActionPerformed

    private void cboPostTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboPostTypeActionPerformed
        if (cboPostType.getSelectedIndex() == 0) {
            pnlImage.setVisible(false);
            pnlText.setVisible(true);
        }
        else {
            pnlImage.setVisible(true);
            pnlText.setVisible(false);
        }//if-else
    }//GEN-LAST:event_cboPostTypeActionPerformed

    private void btnPathInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathInfoActionPerformed
        JFileChooser fc1 = new JFileChooser();

        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter("Image Files", "jpg", "jpeg", "png", "gif"); // Extensions: case-insensitive

        fc1.setFileFilter(imageFilter);

        int result = fc1.showOpenDialog(this);

        File selectedFile = fc1.getSelectedFile();
        if (selectedFile != null) {
            String name = selectedFile.getName();
            String fullpath = selectedFile.getPath();
            File path = fc1.getCurrentDirectory();
            String strPath = path.getAbsolutePath();
            txtFilename.setText(name);
            txtLocation.setText(fullpath);
        } //if
        else {
            JOptionPane.showMessageDialog(null, "No image file selected!", "Attach Image", JOptionPane.OK_OPTION);
        }//else
        
        Path sourcePath = Paths.get(txtLocation.getText());

        Path destination = Paths.get("src/pictures");

        Path destinationPath = destination.resolve(txtFilename.getText());

        try {
            // Validate that the source file exists and is readable
            if (!Files.exists(sourcePath)) {
                System.err.println("Error: Source file does not exist.");
                return;
            }
            if (!Files.isReadable(sourcePath)) {
                System.err.println("Error: Source file is not readable.");
                return;
            }
            // Copy file with REPLACE_EXISTING to overwrite if file already exists
            Files.copy(sourcePath, destinationPath, StandardCopyOption.REPLACE_EXISTING);

            System.out.println("File copied successfully from " 
                               + sourcePath + " to " + destinationPath);

        }//try
        catch (FileAlreadyExistsException e) {
            System.err.println("Error: Destination file already exists.");
        }//catch
        catch (NoSuchFileException e) {
            System.err.println("Error: Source file not found.");
        }//catch
        catch (IOException e) {
            System.err.println("I/O Error: " + e.getMessage());
        }//catch
    }//GEN-LAST:event_btnPathInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmAddPost().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPost;
    private javax.swing.JButton btnPathInfo;
    private javax.swing.JComboBox<String> cboPostSecurity;
    private javax.swing.JComboBox<String> cboPostType;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPostId;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlImage;
    private javax.swing.JPanel pnlText;
    private javax.swing.JTextField txtDescript;
    private javax.swing.JTextField txtFilename;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
