/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.*;

/**
 *
 * @author lpeja
 */
public class FrmLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmLogin.class.getName());
    int countFails = 0;
    /**
     * Creates new form AppLoginScr
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }//FrmLogin

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnLogon = new javax.swing.JButton();
        lblEmail = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        btnShowPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        txtEmail.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N

        btnLogon.setBackground(new java.awt.Color(0, 102, 204));
        btnLogon.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnLogon.setForeground(new java.awt.Color(255, 255, 255));
        btnLogon.setText("Logon");
        btnLogon.addActionListener(this::btnLogonActionPerformed);

        lblEmail.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblEmail.setText("Email:");

        lblPassword.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPassword.setText("Password:");

        txtPwd.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N

        btnShowPass.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnShowPass.setText("Show Password");
        btnShowPass.addActionListener(this::btnShowPassActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmail)
                    .addComponent(lblPassword))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtEmail)
                        .addComponent(btnLogon, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                        .addComponent(txtPwd))
                    .addComponent(btnShowPass))
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPassword)
                    .addComponent(txtPwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(btnShowPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btnLogon, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        AppData.menuScreen.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnLogonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogonActionPerformed
        if (txtEmail.getText().equals("") || txtEmail.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "You have not entered any E-mail!", "Missing Input", JOptionPane.OK_OPTION);
            txtEmail.grabFocus();
            return;
        }
        else if (txtPwd.getText().equals("") || txtPwd.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "You have not entered any password!", "Missing Input", JOptionPane.OK_OPTION);
            txtPwd.grabFocus();
            return;
        }
        
        char [] pwd = txtPwd.getPassword();
        String pwdStr = String.valueOf(pwd);

        boolean tf = AppData.validLogon(txtEmail.getText(), pwdStr);
        
        if (tf) {
            this.dispose();
            AppData.mainScreen = new FrmMain();
            AppData.mainScreen.setVisible(true);
            countFails = 0;
        }
        else {
            countFails++;            
            if(countFails == 5) {
                JOptionPane.showMessageDialog(null, "Too many failed attempts, exiting Yapp...", "Login Unsuccessful", JOptionPane.OK_OPTION);
                System.exit(0);
            }
            else {
                JOptionPane.showMessageDialog(null, "Your password or E-mail was incorrect!\n\nYou have " + (5 - countFails) + " attempts left.", "Login Unsuccessful", JOptionPane.OK_OPTION);
            }//if-else
        }//if-else
    }//GEN-LAST:event_btnLogonActionPerformed

    private void btnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassActionPerformed
        if (txtPwd.getText().equals("") || txtPwd.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "You have not entered any password!", "Your Password", JOptionPane.OK_OPTION);
            txtPwd.grabFocus();
        }
        else
            JOptionPane.showMessageDialog(null, "The password you typed is: \n\n" + txtPwd.getText(), "Your Password", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnShowPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogon;
    private javax.swing.JButton btnShowPass;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPwd;
    // End of variables declaration//GEN-END:variables
}
