/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.JOptionPane;

/**
 *
 * @author lpeja
 */
public class FrmMain extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmMain.class.getName());

    /**
     * Creates new form AppScrMain
     */
    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
        if (AppData.loggedOn.getRegDate().equals( AppData.genDate() ))
            lblWelcome.setText("Welcome to Yapp, " + AppData.loggedOn.getForename() + " " + AppData.loggedOn.getSurname() + "!");
        else
            lblWelcome.setText("Welcome back, " + AppData.loggedOn.getForename() + " " + AppData.loggedOn.getSurname() + "!");
        
        lblDetailHeading.setText("<html>Date of Birth: "
                + "<br><br>Date Registered: "
                + "<br><br>Email: "
                + "</html>");
        lblDetails.setText("<html>" + AppData.loggedOn.getDoB() 
                + "<br><br>" + AppData.loggedOn.getRegDate() 
                + "<br><br>" + AppData.loggedOn.getEmail()
                + "</html>");
        AppData.loggedOn.setLastLogin(AppData.genDateTime());
    }//FrmMain

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        FrmAddPost = new javax.swing.JButton();
        FrmMyPosts = new javax.swing.JButton();
        FrmPublicPosts = new javax.swing.JButton();
        FrmFriendsMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPic = new javax.swing.JLabel();
        lblDetails = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        lblDetailHeading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 0));

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        FrmAddPost.setBackground(new java.awt.Color(102, 153, 0));
        FrmAddPost.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FrmAddPost.setForeground(new java.awt.Color(0, 0, 0));
        FrmAddPost.setText("Add Post");
        FrmAddPost.setBorderPainted(false);
        FrmAddPost.addActionListener(this::FrmAddPostActionPerformed);

        FrmMyPosts.setBackground(new java.awt.Color(102, 153, 0));
        FrmMyPosts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FrmMyPosts.setForeground(new java.awt.Color(0, 0, 0));
        FrmMyPosts.setText("View My Posts");
        FrmMyPosts.setBorderPainted(false);
        FrmMyPosts.addActionListener(this::FrmMyPostsActionPerformed);

        FrmPublicPosts.setBackground(new java.awt.Color(102, 153, 0));
        FrmPublicPosts.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FrmPublicPosts.setForeground(new java.awt.Color(0, 0, 0));
        FrmPublicPosts.setText("Public Posts");
        FrmPublicPosts.setBorderPainted(false);
        FrmPublicPosts.addActionListener(this::FrmPublicPostsActionPerformed);

        FrmFriendsMenu.setBackground(new java.awt.Color(102, 153, 0));
        FrmFriendsMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        FrmFriendsMenu.setForeground(new java.awt.Color(0, 0, 0));
        FrmFriendsMenu.setText("Friends Menu");
        FrmFriendsMenu.setBorderPainted(false);
        FrmFriendsMenu.addActionListener(this::FrmFriendsMenuActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FrmAddPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrmMyPosts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrmPublicPosts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FrmFriendsMenu)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FrmAddPost)
                    .addComponent(FrmMyPosts)
                    .addComponent(FrmPublicPosts)
                    .addComponent(FrmFriendsMenu))
                .addContainerGap())
        );

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/blank-profile-picture-smaller.png"))); // NOI18N

        lblDetails.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblDetails.setText("lblDetails");
        lblDetails.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblDetails.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblWelcome.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(0, 102, 204));
        lblWelcome.setText("lblWelcome");
        lblWelcome.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblWelcome.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblWelcome.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblDetailHeading.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        lblDetailHeading.setText("lblDetailHeading");
        lblDetailHeading.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblDetailHeading.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblDetailHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 264, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblWelcome)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDetailHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblPic))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int choice = JOptionPane.showConfirmDialog(null, "Are you sure you want to quit?", "Confirm Sign Out", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            AppData.menuScreen.setVisible(true);
        }
        else {
            AppData.mainScreen = new FrmMain();
            AppData.mainScreen.setVisible(true);
        }//if-else
    }//GEN-LAST:event_formWindowClosing

    private void FrmAddPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmAddPostActionPerformed
        this.setVisible(false);
        AppData.addPostScreen = new FrmAddPost();
        AppData.addPostScreen.setVisible(true);
    }//GEN-LAST:event_FrmAddPostActionPerformed

    private void FrmMyPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmMyPostsActionPerformed
        this.setVisible(false);
        AppData.myPostsScreen = new FrmMyPosts();
        AppData.myPostsScreen.setVisible(true);
    }//GEN-LAST:event_FrmMyPostsActionPerformed

    private void FrmFriendsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmFriendsMenuActionPerformed
        this.setVisible(false);
        AppData.friendsMenuScreen = new FrmFriendsMenu();
        AppData.friendsMenuScreen.setVisible(true);
    }//GEN-LAST:event_FrmFriendsMenuActionPerformed

    private void FrmPublicPostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FrmPublicPostsActionPerformed
        this.setVisible(false);
        AppData.publicPostsScreen = new FrmPublicPosts();
        AppData.publicPostsScreen.setVisible(true);
    }//GEN-LAST:event_FrmPublicPostsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmMain().setVisible(false));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FrmAddPost;
    private javax.swing.JButton FrmFriendsMenu;
    private javax.swing.JButton FrmMyPosts;
    private javax.swing.JButton FrmPublicPosts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDetailHeading;
    private javax.swing.JLabel lblDetails;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
