/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import java.awt.Toolkit;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author 50122851
 */
public class FrmPublicPosts extends javax.swing.JFrame {
    private DefaultListModel listModel;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPublicPosts.class.getName());

    /**
     * Creates new form FrmPublicPosts
     */
    public FrmPublicPosts() {
        initComponents();
        setLocationRelativeTo(null);
        lblUser.setText(" " + AppData.loggedOn.basicInfo());
        setupCtrls();
    }

    public void setupCtrls() {
        listModel = new DefaultListModel();
        
        for (int index = AppData.postsAL.size()-1; index >= 0; index--) {
            Posts pObj = (Posts) AppData.postsAL.get(index);
            
            if (pObj.getPostSecurity().equals("public"))
                listModel.addElement(pObj.getPostID() + " from [" + pObj.getUserID() + "]");
        }//for
        
        lstPostIDs.setModel(listModel);
        lstPostIDs.setSelectedIndex(0);
    }//setupCtrls

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPostInfo = new javax.swing.JLabel();
        lblPic = new javax.swing.JLabel();
        pnlPosts = new javax.swing.JPanel();
        lblPostIDs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPostIDs = new javax.swing.JList<>();
        cboComments = new javax.swing.JComboBox<>();
        txtComment = new javax.swing.JTextField();
        btnAddComment = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        lblUser.setBackground(new java.awt.Color(255, 255, 255));
        lblUser.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblUser.setForeground(new java.awt.Color(0, 0, 0));
        lblUser.setText("lblUser");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblUser.setOpaque(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(880, 427));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 0));
        jLabel1.setText("Public Posts");

        lblPostInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblPostInfo.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        lblPostInfo.setForeground(new java.awt.Color(0, 0, 0));
        lblPostInfo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lblPostInfo.setAlignmentX(0.5F);
        lblPostInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        lblPostInfo.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        lblPostInfo.setOpaque(true);
        lblPostInfo.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/blank-profile-picture-smaller.png"))); // NOI18N

        pnlPosts.setBackground(new java.awt.Color(255, 255, 255));
        pnlPosts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        pnlPosts.setForeground(new java.awt.Color(255, 255, 255));

        lblPostIDs.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        lblPostIDs.setForeground(new java.awt.Color(102, 204, 0));
        lblPostIDs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPostIDs.setText("Blogs");
        lblPostIDs.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lstPostIDs.setBackground(new java.awt.Color(255, 255, 255));
        lstPostIDs.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 12)); // NOI18N
        lstPostIDs.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPostIDsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstPostIDs);

        javax.swing.GroupLayout pnlPostsLayout = new javax.swing.GroupLayout(pnlPosts);
        pnlPosts.setLayout(pnlPostsLayout);
        pnlPostsLayout.setHorizontalGroup(
            pnlPostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPostsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lblPostIDs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPostsLayout.setVerticalGroup(
            pnlPostsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPostsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPostIDs, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        cboComments.setBackground(new java.awt.Color(255, 255, 255));
        cboComments.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        cboComments.setForeground(new java.awt.Color(0, 0, 0));
        cboComments.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        cboComments.setOpaque(true);

        txtComment.setBackground(new java.awt.Color(255, 255, 255));
        txtComment.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        txtComment.setForeground(new java.awt.Color(0, 0, 0));
        txtComment.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));

        btnAddComment.setBackground(new java.awt.Color(0, 102, 204));
        btnAddComment.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        btnAddComment.setForeground(new java.awt.Color(255, 255, 255));
        btnAddComment.setText("Add Comment");
        btnAddComment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCommentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 542, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtComment)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnAddComment))
                                .addComponent(cboComments, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPostInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(pnlPosts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlPosts, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPostInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboComments, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtComment)
                            .addComponent(btnAddComment, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstPostIDsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPostIDsValueChanged
        String pidStr = listModel.get(lstPostIDs.getSelectedIndex()).toString().substring(0,5);
        int pid = Integer.valueOf(pidStr);
        
        Posts thePost = AppData.findPost(pid);
        lblPostInfo.setText(thePost.details());
        
        Posts pObj = (Posts) AppData.postsAL.get(lstPostIDs.getSelectedIndex());
        cboComments.removeAllItems();

        if (pObj.getComments().size() == 0)
            cboComments.addItem("No Comments Yet!");

        else {
            for(Object obj : pObj.getComments())
                cboComments.addItem(obj.toString());
        }//if-else

        try {
            Image imgObj = (Image) pObj;
            java.awt.Image pic;
            pic = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/pictures/" + imgObj.getImageName()));
            //scale to label size
            pic = pic.getScaledInstance(lblPostInfo.getWidth(), lblPostInfo.getHeight(), 2);

            lblPostInfo.setIcon(new ImageIcon(pic));
        }//try
        catch(Exception ex) {
            System.out.println(ex.toString());
        }//catch
    }//GEN-LAST:event_lstPostIDsValueChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        AppData.mainScreen.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnAddCommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCommentActionPerformed
        Posts pObj = (Posts) AppData.postsAL.get(lstPostIDs.getSelectedIndex());
        if (pObj.getComments().size() == 0)
            cboComments.removeAllItems();

        pObj.addComment("<html>" + AppData.loggedOn.basicInfo() + " " + AppData.genDateTime() + "<br><br>" + txtComment.getText() + "</html>");
        cboComments.addItem("<html>" + AppData.loggedOn.basicInfo() + " " + AppData.genDateTime() + "<br><br>" + txtComment.getText() + "</html>");
        txtComment.setText("");
    }//GEN-LAST:event_btnAddCommentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPublicPosts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddComment;
    private javax.swing.JComboBox<String> cboComments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblPostIDs;
    private javax.swing.JLabel lblPostInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUser;
    private javax.swing.JList<String> lstPostIDs;
    private javax.swing.JPanel pnlPosts;
    private javax.swing.JTextField txtComment;
    // End of variables declaration//GEN-END:variables
}
