/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oopa2;

import javax.swing.*;

/**
 *
 * @author lpeja
 */
public class FrmRegister extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmRegister.class.getName());

    /**
     * Creates new form AppRegisterScr
     */
    public FrmRegister() {
        initComponents();
        setLocationRelativeTo(null);
        setupCtrls();
    }//FrmRegister

    public void setupCtrls() {
        int rnd = (int)(Math.random() * (9999 - 1000 + 1)) + 1000;
        while(AppData.isUniqueUID(rnd) == false)
            rnd = (int)(Math.random() * (9999 - 1000 + 1)) + 1000;
        
        String uid = String.valueOf(rnd);
        lblUID.setText(uid);
        
        txtForename.setText("");
        txtSurname.setText("");
        cboDay.setSelectedIndex(0);
        cboMonth.setSelectedIndex(0);
        jSlider1.setValue(0);
        lblYear.setText("Year");

        lblRegistered.setText(AppData.genDate());
    }//setupCtrls
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtSurname = new javax.swing.JTextField();
        txtForename = new javax.swing.JTextField();
        lblForename = new javax.swing.JLabel();
        lblSurname = new javax.swing.JLabel();
        lblDob = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        cboDay = new javax.swing.JComboBox<>();
        cboMonth = new javax.swing.JComboBox<>();
        lblPassword = new javax.swing.JLabel();
        pwdPassword = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lblLast = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblRegistered = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblFriends = new javax.swing.JLabel();
        chkLocked = new javax.swing.JCheckBox();
        lblUIDtext = new javax.swing.JLabel();
        lblUID = new javax.swing.JLabel();
        lblPicture = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        lblYear = new javax.swing.JLabel();
        btnShowPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Yapp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTitle.setBackground(new java.awt.Color(204, 255, 51));
        lblTitle.setFont(new java.awt.Font("Ravie", 1, 48)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setText("  yapp");
        lblTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTitle.setOpaque(true);

        txtSurname.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        txtForename.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblForename.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblForename.setText("First Name:");

        lblSurname.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblSurname.setText("Surname:");

        lblDob.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblDob.setText("Date Of Birth:");

        txtEmail.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblEmail.setText("Email:");

        cboDay.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cboDay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cboMonth.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        cboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMonth.addActionListener(this::cboMonthActionPerformed);

        lblPassword.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblPassword.setText("Password:");

        pwdPassword.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N

        btnSignUp.setBackground(new java.awt.Color(0, 102, 204));
        btnSignUp.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        btnSignUp.setForeground(new java.awt.Color(255, 255, 255));
        btnSignUp.setText("Sign Up");
        btnSignUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSignUp.addActionListener(this::btnSignUpActionPerformed);

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel11.setText("Last login:");

        lblLast.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblLast.setText("N/A");

        jLabel12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel12.setText("Registered:");

        lblRegistered.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jLabel13.setText("Friends:");

        lblFriends.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblFriends.setText("0");

        chkLocked.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        chkLocked.setText("Locked");

        lblUIDtext.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        lblUIDtext.setText("User ID:");

        lblUID.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lblUID.setText(" ");

        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pictures/blank-profile-picture-973460_1280.png"))); // NOI18N
        lblPicture.setText(" ");

        jSlider1.setMaximum(2013);
        jSlider1.setMinimum(1909);
        jSlider1.addChangeListener(this::jSlider1StateChanged);

        lblYear.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        lblYear.setText("Year");
        lblYear.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        lblYear.setPreferredSize(new java.awt.Dimension(64, 22));
        lblYear.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        btnShowPass.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 12)); // NOI18N
        btnShowPass.setText("Show Password");
        btnShowPass.addActionListener(this::btnShowPassActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(lblPassword)
                    .addComponent(lblEmail)
                    .addComponent(lblDob)
                    .addComponent(lblSurname)
                    .addComponent(lblForename)
                    .addComponent(lblUIDtext))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtForename, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUID, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(chkLocked, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFriends, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnShowPass, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblLast, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUIDtext)
                    .addComponent(lblUID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblForename)
                    .addComponent(txtForename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSurname))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblDob)
                    .addComponent(cboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowPass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chkLocked)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblLast, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(lblRegistered, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(lblFriends))
                .addGap(18, 18, 18)
                .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.dispose();
        AppData.menuScreen.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        //perform validation
        
        if (txtForename.getText().equals("") || txtForename.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Your forename cannot be blank!", "Missing Input", JOptionPane.OK_OPTION);
            txtForename.grabFocus();
            return;
        }//Forename presence check
        
        else if (txtSurname.getText().equals("") || txtSurname.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Your surname cannot be blank!", "Missing Input", JOptionPane.OK_OPTION);
            txtSurname.grabFocus();
            return;
        }//Surname presence check
        
        else if (cboDay.getSelectedIndex() == 0 || cboMonth.getSelectedIndex() == 0 || lblYear.getText().equals("Year")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Date of Birth!", "Invalid Date of Birth", JOptionPane.OK_OPTION);
            if (cboDay.getSelectedIndex() == 0)
                cboDay.grabFocus();            
            else if (cboMonth.getSelectedIndex() == 0)
                cboMonth.grabFocus();            
            else
                jSlider1.grabFocus();            
            return;
        }//Date of Birth
        
        else if (txtEmail.getText().equals("") || txtEmail.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Your e-mail cannot be blank!", "Missing Input", JOptionPane.OK_OPTION);
            txtEmail.grabFocus();
            return;
        }//E-mail presence check
        
        else if (txtEmail.getText().indexOf("@") == -1 && txtEmail.getText().indexOf(".") == -1) {
            JOptionPane.showMessageDialog(null, "You have no @ or .com domain! Please enter a valid e-mail!", "Invalid E-mail", JOptionPane.OK_OPTION);
            txtEmail.grabFocus();
            return;
        }//else-if checking presence of '@' and '.'
        
        else if ( txtEmail.getText().indexOf("@") == 0 || txtEmail.getText().indexOf(".") == 0 || txtEmail.getText().endsWith("@") || txtEmail.getText().endsWith(".") ) {
            JOptionPane.showMessageDialog(null, "You cannot have your @ or '.' at the start or end of your email! Please enter a valid e-mail!", "Invalid E-mail", JOptionPane.OK_OPTION);
            txtEmail.grabFocus();
            return;
        }//else-if checking '@' and '.' are not at the beginning or end of email input
        
        else if (txtEmail.getText().endsWith(".com") == false) {
            JOptionPane.showMessageDialog(null, "Your email should end with a '.com' domain! Please enter a valid e-mail!", "Invalid E-mail", JOptionPane.OK_OPTION);
            txtEmail.grabFocus();
            return;
        }//else-if checking email input ends with ".com"
        
        else if (pwdPassword.getText().equals("") || pwdPassword.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Your password cannot be blank!", "Missing Input", JOptionPane.OK_OPTION);
            pwdPassword.grabFocus();
            return;
        }//end of if-else-if chain
                   
        //create user object
        //String userID, String forename, String surname, String dob, String email, String password, boolean locked, String lastLogin, String regDate, int friends
        String birthday = cboDay.getSelectedIndex() + "/" + cboMonth.getSelectedIndex() + "/" + lblYear.getText();
        int id = Integer.valueOf(lblUID.getText());
        User temp = new User(id, txtForename.getText(), txtSurname.getText(), birthday, txtEmail.getText(), pwdPassword.getText(), lblRegistered.getText());
        
        if(chkLocked.isSelected())
            temp.setLocked(true);
        else
            temp.setLocked(false);
        
        int ans = JOptionPane.showConfirmDialog(null, "Please check your details now before creating your account.\n\nDo you want to proceed?", "Confirm Account Creation", JOptionPane.YES_NO_OPTION);

        if (ans == 0) {
            AppData.usersAL.add(temp);
            JOptionPane.showMessageDialog(null, "You have successfully created an account!", "Account Created", JOptionPane.INFORMATION_MESSAGE);
            setupCtrls();
            this.dispose();
            AppData.menuScreen.setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null, "Account creation has been cancelled.", "Account Creation Aborted", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int value = jSlider1.getValue();
        lblYear.setText(String.valueOf(value));
    }//GEN-LAST:event_jSlider1StateChanged

    private void btnShowPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPassActionPerformed
        if (pwdPassword.getText().equals("") || pwdPassword.getText().isBlank())
            JOptionPane.showMessageDialog(null, "Your password is empty!", "Your Password", JOptionPane.OK_OPTION);
        else
            JOptionPane.showMessageDialog(null, "The password you typed is: \n\n" + pwdPassword.getText(), "Your Password", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnShowPassActionPerformed

    private void cboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonthActionPerformed
        
        //NOTICE - Search "java jframe calendar date picker using comboboxes" and click "How can i make a calendar using JComboBox?"
        
        if (lblYear.getText().equals("Year") == false) {
            int year = Integer.valueOf(lblYear.getText());
            boolean leapyear = false;
            
            if (cboMonth.getSelectedIndex() == 4 || cboMonth.getSelectedIndex() == 6 || cboMonth.getSelectedIndex() == 9 || cboMonth.getSelectedIndex() == 11) {
                switch (cboDay.getItemCount()) {
                    case 31:
                        cboDay.removeItemAt(31); //Remove 31st day if selected month has less than 31 days
                        System.out.println("cheese2");
                        break;
                //else-if
                    case 28:
                        //re-add days to month if previous selected month was February
                        cboDay.addItem("29");
                        cboDay.addItem("30");
                        break;
                //re-add days to month if previous selected month was February - Leap Year
                    case 29:
                        cboDay.addItem("30");
                        break;
                    default:
                        break;
                }//switch
            }
            else if (cboMonth.getSelectedIndex() == 2) {
                if (cboDay.getItemCount() == 31)
                    cboDay.removeItemAt(31);
                
                cboDay.removeItemAt(30); //Remove 30th day if selected month is February

                //leap year validation
                if (year % 4 == 0) { // every year exactly divisible by 4 is a leap year
                    if (year % 100 == 0) // except for years exactly divisible by 100
                        if (year % 400 == 0) // unless they are exactly divisible by both 100 and 400, then they are leap years
                            leapyear = true;
                    leapyear = true;
                }//nested if

                //Remove February 29th for non-leap years
                if (leapyear == false)
                    cboDay.removeItemAt(29);
            }//if-else-if
            
            else if (cboDay.getItemCount() == 30 && (cboMonth.getSelectedIndex() != 4 || cboMonth.getSelectedIndex() != 6 || cboMonth.getSelectedIndex() != 9 || cboMonth.getSelectedIndex() != 11)) //re-add days to month if previous selected month has less than 31 days
                System.out.println("cheese3");
                cboDay.addItem("31");
        }//nested if
    }//GEN-LAST:event_cboMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmRegister().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowPass;
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox<String> cboDay;
    private javax.swing.JComboBox<String> cboMonth;
    private javax.swing.JCheckBox chkLocked;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblDob;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblForename;
    private javax.swing.JLabel lblFriends;
    private javax.swing.JLabel lblLast;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblRegistered;
    private javax.swing.JLabel lblSurname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUID;
    private javax.swing.JLabel lblUIDtext;
    private javax.swing.JLabel lblYear;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtForename;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables
}
